### ISSUE TITLE
Make pronto able to run as a micro server for the GitHub integration

### ISSUE THREAD

**Issue by jeromedalbert** [prontolabs/pronto#105]
The idea would be to have commands like `rackup` (with a `config.ru` file) or `pronto server` or `pronto watch`. This micro server would listen to Github webhooks when PR events happen, and analyze the PR.

This would allow people to easily have their own free version of https://houndci.com by deploying it to a free Heroku dyno or any other server. This also has the advantage of being independent from a CI server and it does not require too much effort to give it a spin.

I do not know if this is in the scope of the pronto project though. This [small 60-lines Sinatra server](https://github.com/VicinityCommerce/watchdog/blob/master/app.rb) I wrote basically just wraps pronto, so I was thinking it would not be too much effort to integrate it in this project. The server works quite well, it is on a free Heroky dyno and we use it every day at my job.

If this is not in the scope of this project and these kinds of servers should be independent, please close this enhancement request. If it is, I could maybe find some time to make a PR (although I do not guarantee anything).

**Comment by gkop** [comment]
Thanks for creating this issue and keeping it open.

I was disappointed to discover that CircleCI doesn't very well support running Pronto inline because it doesn't allow you to wait until a PR is opened to begin a build against a branch on your origin (cf. [here](https://discuss.circleci.com/t/feature-request-option-to-disable-builds-on-commit-pushes/682/11), [here](https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213), and [here](https://discuss.circleci.com/t/feature-request-option-to-disable-builds-on-commit-pushes/682).

Looking forward to playing with your Sinatra script.

**Comment by mmozuras** [comment]
For reference, there's also this Pronto-as-a-Service project by @doomspork: https://github.com/wombatsecurity/nag

**Comment by jeromedalbert** [comment]
I'm gonna close this PR for now, since there does not seem to be much demand for it.

Also, my main use case for using a Pronto-as-a-Service is moot, since these days I am using pronto directly with my CI server (Codeship) thanks to the trick explained in [this blog post](https://christoph.luppri.ch/articles/2017/03/05/how-to-automatically-review-your-prs-for-style-violations-with-pronto-and-rubocop).

As explained in the post, Codeship doesn't provide a pull request environment variable, but you can use `git ls-remote` to query remote PR branches made by Github, and do a bit of extraction with `sed`: 

```bash
export PRONTO_PULL_REQUEST_ID="$(git ls-remote -q origin pull\*\head | grep $CI_COMMIT_ID | sed 's/.*refs\/pull\/\([0-9]*\)\/head/\1/g')"
```
