### ISSUE TITLE
How to run pronto on the entire source tree?

### ISSUE THREAD

**Issue by ghost** [prontolabs/pronto#17]
I would like to run pronto on the entire source tree (for the initial run) - how would I do that?

**Comment by ivantsepp** [comment]
@mmozuras any chance in reconsidering this? This would be a nice option to have as pronto would be a wrapper for all the linters you may have on a project. For ex, `pronto run` would show me ruby, scss, and js lint errors instead of me running the respective individual tools.

**Comment by mmozuras** [comment]
@ivantsepp If I'd decide to implement it, I'd be faced with two choices:
* keeping the current way pronto works. But that would result in abysmal performance. Pronto is optimised for a certain scenario. Running it for entire source tree would take orders of magnitude longer than running those tools separately.
* implementing it in completely different way. But that basically means writing a new gem :smile:.

**Comment by ivantsepp** [comment]
Thanks for the speedy reply @mmozuras ! The idea I have is that you can set the different levels of running pronto. The default will check the diff only. The next level could check the entire file (so if you modified a file, you are responsible for fixing lint errors for the file). Then the last level would be the entire source. Maybe there can be a configuration so that pronto would run certain rules for each level?

What are you thoughts on this idea? I am certainly interested in coming up with a PR for this if there's not enough detail above.

**Comment by mbajur** [comment]
Would be amazing to have an option to have pronto as a wrapper for all the linters :)
